### ISSUE TITLE
Usage of the files

### ISSUE THREAD

**Issue by rachittt** [Swetabhsuman8/instagram-hacking-tool#1]
I couldn't find a way to use these files moreover while experimenting the login.html file directs to login.php however it should directly open instagram.com so please check on it and it would be easier for the user to use your tool  if you put a guideline on this project as well to make your tool easier to use and helpful otherwise its a very good idea :)

**Comment by jasmineramona** [comment]
I specialise in Instagram hacking. Contact me if you need paid help. (jasmineramona@protonmail.com)
